### ISSUE TITLE
Add custom ImageGoNord EXIF as metadata and origin

### ISSUE THREAD

**Issue by TheJoin95** [Schroedinger-Hat/ImageGoNord-pip#17]
I'm tired to see all the images across the subreddit, twitter, desktop, slide presentation, podcast and so on without a credit to us neither a link or a tag.

It was ok at the beginning but we are seeing too many people gaining on our service and work.
A custom exif is, of course, not that great to guarantee the credit but at least it's something that almost no one would take care, but still.

Thank for supporting this project, we are spending some money on our VPS to make the service available to anyone and anywhere and we are gonna keep it. Please, if you read this, please please please: put a link on us, thanks for sharing

ref: https://exiv2.org/tags.html

**Comment by TheJoin95** [comment]
I'm leaving it here as it could be a good first issue

**Comment by Hierosme** [comment]
Tee goal is to add a meta during post processing ?

**Comment by TheJoin95** [comment]
Yes, the goal Is ti add a kind of tag or "edit by" tag to the

**Comment by TheJoin95** [comment]
I'm taking care of this with a first iteration
